{{- $toolPrefix := include "tool-config.NAME" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tool-config.config-name" . }}
  labels:
    app: {{ include "tool-config.app" . }}
    app.kubernetes.io/name: {{ include "tool-config.app" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/part-of: {{ include "tool-config.app" . }}
    app.kubernetes.io/component: {{ .Values.component | quote }}
    chart: {{ include "tool-config.chart" . }}
    release: {{ .Release.Name | quote }}
    group: {{ .Values.group | quote }}
    grouping: {{ .Values.grouping | quote }}
  annotations:
    description: {{ printf "Config map to hold the url for %s in the environment so that other components can access it" (include "tool-config.name" .) }}
data:
  {{ $toolPrefix }}_URL: {{ .Values.url | quote }}
  {{- range $key, $val := .Values.otherConfig }}
  {{ printf "%s_%s" $toolPrefix (upper $key) }}: {{ $val | quote }}
  {{- end }}
