apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ include "cluster.name" . }}
  namespace: {{ include "cluster.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
    helm.sh/hook-weight: "120"
spec:
  clusterName: {{ include "cluster.name" . }}
  clusterNamespace: {{ include "cluster.namespace" . }}
  clusterLabels:
    cloud: {{ include "cloud.provider" . }}
    vendor: {{ include "cluster.vendor" . }}
  applicationManager:
    proxyPolicy: OCPGlobalProxy
    enabled: true
  policyController:
    proxyPolicy: OCPGlobalProxy
    enabled: true
  searchCollector:
    proxyPolicy: OCPGlobalProxy
    enabled: true
  certPolicyController:
    proxyPolicy: OCPGlobalProxy
    enabled: true
  iamPolicyController:
    proxyPolicy: OCPGlobalProxy
    enabled: true

