# Default values for ibm-cpd-platform-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: ibmcpd-cr
spec:
  license:
    accept: true
    license: Enterprise
  storageClass: managed-nfs-storage