language: shell
before_install:
  - sudo curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
script:
  - ./scripts/package.sh ${PUBLISH_DIR}
  - ./scripts/publish.sh ${PUBLISH_BRANCH} ${PUBLISH_DIR} ${REPO_URL}
git:
  depth: false
env:
  global:
    - PUBLISH_BRANCH=gh-pages
    - PUBLISH_DIR=publish
    - REPO_URL=https://ibm-garage-cloud.github.io/toolkit-charts/
branches:
  - master
