# Default values for slack-notifications.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/ibmgaragecloud/slack-notifications
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

container:
  port: 8080

service:
  port: 80

broker:
  name: default

secret:
  # provide name of the secret that contains slack url
  name: slack_url
  # provide key of the secret that contains slack url
  key: SLACK.URL

triggers: 
  - name: taskrun-success-trigger
    type: dev.tekton.event.taskrun.successful.v1
  - name: taskrun-fail-trigger
    type: dev.tekton.event.taskrun.failed.v1
  - name: pipelinerun-success-trigger
    type: dev.tekton.event.pipelinerun.successful.v1
  - name: pipelinerun-fail-trigger
    type: dev.tekton.event.pipelinerun.failed.v1
