# Default values for tool-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app: catalyst
group: catalyst-tools

component: "tools"

name: ""
url: ""
username: ""
password: ""
