# Default values for tool-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ingressSubdomain: ""

# the name of the application the config is part of (used for app label)
app: ""
group: "catalyst-tools"
grouping: "garage-cloud-native-toolkit"

component: "tools"

name: ""
displayName: ""
url: ""
host: ""
includeNamespace: true
username: ""
password: ""

ingressSubdomain: ""
applicationMenu: false
section: "Cloud-Native Toolkit"
imageUrl: ""

otherConfig: {}
otherSecrets: {}