# Default values for ibm-eventstreams-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

subscriptions:
  ibmeventstreams:
    name: ibm-eventstreams
    subscription:
      channel: v2.2-eus
      installPlanApproval: Automatic
      name: ibm-eventstreams
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace
