# Default values for argocd-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  ingressSubdomain: ""
  tlsSecretName: ""
  clusterType: ""

nameOverride: ""

olmNamespace: ""
operatorNamespace: ""

clusterType: ""

ocpCatalog:
  source: redhat-operators
  channel: ocp-4.4
  name: openshift-pipelines-operator-rh
operatorHub:
  source: ""
  channel: ""
  name: ""

createdBy: ""

tektonNamespace: "openshift-pipelines"
