infrastructureId: ""

cloudProvider:
  name: "" # aws, azure, ibmcloud or vsphere
  managed: false # for roks, aro, rosa set to true

vsphere:
  networkName: 
  datacenter: 
  datastore: 
  cluster: 
  server: 
  zones:
    - 1
  infraNodes:
    nodeCount:
    diskGiB:
    memoryMiB:
    numCPUs:
    numCoresPerSocket:
  storageNodes:
    nodeCount:
    diskGiB:
    memoryMiB:
    numCPUs:
    numCoresPerSocket:
  cloudpakNodes:
    nodeCount:
    diskGiB:
    memoryMiB:
    numCPUs:
    numCoresPerSocket:
  folder:
  resourcePool:

cloud:
  region: 
  zones: {}
  image:
  resourceGroup:
  networkResourceGroup:
  virtualNetwork:
  workerSubnet:
  infraNodes:
    nodeCount:
    volumeSize:
    volumeType:
    instanceType:
    taints:
    labels:
  storageNodes:
    nodeCount:
    volumeSize:
    volumeType:
    instanceType:
    taints:
    labels:
  cloudpakNodes:
    nodeCount:
    volumeSize:
    volumeType:
    instanceType:
    taints:
    labels:

global:
  infraNodes:
    taints:
      - effect: "NoSchedule"
        key: "infra"
        value: ""
    labels:
      node-role.kubernetes.io/infra: ""
  storageNodes:
    taints:
      - effect: "NoSchedule"
        key: "node.ocs.openshift.io/storage"
        value: "true"
    labels:
      node-role.kubernetes.io/storage: ""
      cluster.ocs.openshift.io/openshift-storage: ""
  cloudpakNodes:
    taints:
    labels:
      node-role.kubernetes.io/cp4x: ""
