# Default values for ocp-service-tls.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

job:
  repository: ibmgaragecloud/ibmcloud-dev
  tag: 1.2.2
  autoApproveCsr: true

serviceAccount:
  name: job-service-annotation
  create: true
  rbac: true

serviceName: ""
secretName: ""
caConfigName: ""

syncWave: "-3"
