# Default values for argocd-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  ingressSubdomain: ""
  tlsSecretName: ""
  clusterType: ""

nameOverride: ""

olmNamespace: ""
operatorNamespace: ""

clusterType: ""

ocpCatalog:
  source: community-operators
  channel: alpha
  name: nexus-operator-m88i
operatorHub:
  source: operatorhubio-catalog
  channel: alpha
  name: nexus-operator-m88i

serviceAccount: ""
host: ""
app: ""