apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibmcloud.config-name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ibmcloud.name" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Values.app }}
    chart: {{ include "ibmcloud.chart" . }}
    release: {{ .Release.Name }}
    group: {{ .Values.group }}
  annotations:
    description: "ConfigMap to hold the ibmcloud configuration values used to access the cluster environment (so that processes within the cluster can operate on the cluster)"
data:
  CLUSTER_TYPE: {{ include "ibmcloud.cluster_type" . }}
  APIURL: {{ .Values.apiurl | quote }}
  REGISTRY_URL: {{ .Values.registry_url | quote }}
  REGION: {{ .Values.region | quote }}
  SERVER_URL: {{ required "The 'server_url' is required!" .Values.server_url | quote }}
  RESOURCE_GROUP: {{ required "The 'resource_group' is required!" .Values.resource_group | quote }}
  INGRESS_SUBDOMAIN: {{ required "The 'ingress_subdomain' is required!" .Values.ingress_subdomain | quote }}
  REGISTRY_NAMESPACE: {{ include "ibmcloud.registry_namespace" . }}
  CLUSTER_NAME: {{ include "ibmcloud.cluster_name" . }}
  TLS_SECRET_NAME: {{ include "ibmcloud.tls_secret_name" . }}
