# Default values for ocp-console-notification.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ## The type of cluster. If the value is empty string or ocp4 the ConsoleNotification will be created
  clusterType: ""

## The name of the ConsoleNotification resource in the cluster
name: ""

## The background color that should be used for the banner
backgroundColor: purple
## The color of the text that will appear in the banner
color: "#fff"
## The location of the banner. Options: BannerTop, BannerBottom, BannerTopBottom
location: BannerTop
## The text that should be displayed in the banner. This value is required (and the whole point of creating a ConsoleNotification in the first place)
text: ""
